### PR TITLE
Add TuYa Thermostat Radiator Valve support

### PR DESCRIPTION
**Pull request by DawidMartenczuk**
- Simple, but bit of configurable Thermostat Service with zigbee2mqtt `climate` (`system_mode`, `current_heating_setpoint`, `local_temperature`) support
- TuYa TS0601_thermostat support
- SystemMode type

### CODE REVIEW

**Comment by madchicken** [comment]
@DawidMartenczuk Please, fix conflicts so I can merge it if you confirm it is working with the device

**Comment by madchicken** [comment]
@DawidMartenczuk did you see this? https://github.com/madchicken/homebridge-zigbee-nt/issues/83

**Comment by JakubTHOC** [comment]
Hi @DawidMartenczuk are you going to resolve conflicts?
I'm also interested in this extension to Tuya TRV's

**Comment by maccoylton** [comment]
I  submitted a versions for tuya compatible with v2 and it is now merged and published in v2.0.3, have you tried that?

**Comment by madchicken** [comment]
After resolving conflicts, I can say we can close this.

**Pull request closed without merging**
