### PR TITLE
Blitzwolf (_TZ3000_g5xawfcq) Smart Socket BW-SHP13 (TS0121) Support

### PR DESCRIPTION
**Pull request by prugala**
Support for Blitzwolf Smart Socket BW-SHP13:
https://www.blitzwolf.com/ZigBee-3.0-Smart-Socket-EU-p-518.html

Device is dectected as:
manufacturer: _TZ3000_g5xawfcq
model: TS0121

Issue: #113

### CODE REVIEW

**Review by madchicken — CHANGES_REQUESTED** [review]
You don't need the class but just the config in database.ts

**Comment by prugala** [comment]
@madchicken done, I've removed device class.

**Review by madchicken — APPROVED** [review]

**Comment by madchicken** [comment]
@prugala Can you also try the 2.1.0-unstable.2 release? It should work even without this modification. Thanks!

**Comment by prugala** [comment]
@madchicken sorry I didn't see notification on github about your comment. It works on beta without my mr :)

I have question. My socket supports electricity monitoring but didn't work with this plugin (in homekit and eve app). Should I create custom device with support this endpoint?
sc

**Comment by madchicken** [comment]
The plugin is already able to read tose properties, but we need Fakegato integration to be able to see data in EVE app. See issue https://github.com/madchicken/homebridge-zigbee-nt/issues/39

**Pull request merged**
