### PR TITLE
[Bug fixing] Fix various issues

### PR DESCRIPTION
**Pull request by madchicken**
Fix issue #203 (configure issue)
Fix issue #206 (configure issue)
Fix issue #204 (Logger problem)

### CODE REVIEW

**Comment by cal6** [comment]
Would you mind releasing it also? :)

**Comment by madchicken** [comment]
Damn, sorry...I'll do it now

**Comment by cal6** [comment]
Sorry for bugging - but still not released? :)

**Comment by madchicken** [comment]
Hey @cal6 the release happened a while ago here https://github.com/madchicken/homebridge-zigbee-nt/releases/tag/v2.5.5
When you asked I though you were referring to the missing release tag, so I added it.
The NPM package is here: https://www.npmjs.com/package/homebridge-zigbee-nt/v/2.5.5
Let me know if there is some problem with that release, I can do it again. In any case, I have a couple of new commits I want to release soon, so expect a 2.5.6 version to be pushed in few days

**Pull request merged**
